### ISSUE TITLE
After Downloading , I cannot see this plugin in Kibana

### ISSUE THREAD

**Issue by vg15** [logzio/kibana-visualizations#1]
Hi ,

First of all thanks for providing this wonderful plugin,please treat this as a comment not as an issue as I am new to ELK and I was wondering how I can show this plugin on my local Kibana. My environment is 

OS:- Windows 8
Kibana:- 4.1.2
ES:- 1.7.3

I have downloaded "traffic_light_vis" folder and place it in my kibana plugin folder . Now after restart kibana I cannot see this on my kiaban page ? Can you please guide me what I am missing ?

Thanks
VG

**Comment by gillyb** [comment]
Hey,
First, Did you actually restart the kibana server, or just do a refresh in the browser ? (You'll probably need the former).
When you go to the "Visualization" page, do you see any client side errors in the dev tools ?
Finally, please contact me via email (gilly@logz.com) It will be more comfortable to chat over mail.

**Comment by vg15** [comment]
Not able contact you on mentioned email gilly@logz.com . I tried to send you an email from my Gmail account .

**Comment by gillyb** [comment]
oh, :-| My mistake, it's gilly@logz.io
